kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: echo-lb
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
  - role: worker
    labels:
      category: tools
  - role: worker
    labels:
      category: api
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
