apiVersion: v1
kind: Namespace
metadata:
  name: echo
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-tls
  namespace: cert-manager
spec:
  secretName: kube-tls
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
    - 'echo-lb.kube'
    - '*.echo-lb.kube'
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: echo-lb-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
